作業目標<br>
在一個陣列中放入多屬性陣列，進一步對陣列做運算<br>
作業重點<br>
在建立結構化陣列前需要先設定屬性，在做運算時須注意資料屬性

1.題目:<br>
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']<br>
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']<br>
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]<br>
rank_list = [8,1,5,4,7,6,2,3]<br>
myopia_list = [True,True,False,False,True,True,False,False]<br>
1. 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]<br>
2. 呈上題，將array中體重(weight)數據集取出算出全部平均體重
3. 呈上題，進一步算出男生(sex欄位是boy)平均體重、女生(sex欄位是girl)平均體重

In [8]:
import numpy as np 

In [9]:
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

In [10]:
#(1). 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]
student_type = {'names':('name', 'sex', 'weight', 'rank', 'myopia'), 'formats':('U10','U6','f8','i4','?')}
students = np.zeros(8,dtype=student_type)
students['name'] = name_list
students['sex'] = sex_list
students['weight'] = weight_list
students['rank'] = rank_list
students['myopia'] = myopia_list

In [11]:
#(2). 呈上題，將array中體重(weight)數據集取出算出全部平均體重
np.mean(students['weight'])

69.8375

In [12]:
#(3). 呈上題，進一步算出男生(sex欄位是boy)平均體重
boy_index = np.where(students['sex']=='boy')[0]
np.mean(students['weight'][boy_index])

77.18333333333332

In [13]:
#(3). 呈上題，進一步算出女生(sex欄位是girl)平均體重
girl_index = np.where(students['sex']=='girl')[0]
np.mean(students['weight'][girl_index])

47.8

2.請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

print(np.zeros((2, 3)))
print(np.empty((2, 3)))

np.zeros((2, 3)) 會產生真正的 0；np.empty((2, 3)) 會產生一個近似於 0 的陣列。
np.empty 可以用於只是想要初始化，但之後就會數值覆寫過的形況。

3. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。

In [14]:
a = np.random.rand(2, 3)
a = a * 100
print(a)

[[22.36347336 34.87198087 10.55794931]
 [86.45438208 47.27964486 75.62177913]]


In [15]:
#Answer
print(a.round())
print(np.round(a))

[[22. 35. 11.]
 [86. 47. 76.]]
[[22. 35. 11.]
 [86. 47. 76.]]


4. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

In [16]:
m = 20
n = 40

a = np.random.rand(2, 3) * (n - m)
b = a

print((a - b % 1) + m)

[[24. 23. 25.]
 [30. 36. 36.]]
