作業

題目:<br>
array1 = np.array([[10, 8], [3, 5]]) <br>
1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

In [1]:
import numpy as np

In [2]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
#是，雖然算出來沒有完全等於[[1,0],[0,1]]，因為反矩陣計算浮點數的關係所以不會完全等於
array1 = np.array([[10, 8], [3, 5]])
array1_inv = np.linalg.inv(array1)
np.dot(array1_inv,array1)

array([[1., 0.],
       [0., 1.]])

In [3]:
#2. 運用上列array計算特徵值、特徵向量?
w, v = np.linalg.eig(array1)
print("eigenvalues ",w)
print("eigenvactors ",v)

eigenvalues  [13.  2.]
eigenvactors  [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [4]:
#3. 運用上列array計算SVD?
np.linalg.svd(array1)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))

# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 100 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

In [5]:
import numpy as np

In [6]:
Z = np.random.randint(0, 100, 1000000).reshape(100, 100, 100)

In [ ]:
%timeit -n 10 a = 2
for i in Z:
    for j in i:
        for k in j:
            i = i + 1

In [ ]:
%timeit -n 10 a = 2
for i in Z.flat:
    i = i+1

In [ ]:
%timeit -n 10 a = 2
for i in np.nditer(Z):
    i = i+1

### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

In [ ]:
Z = np.random.randint(0,10,50)
print(Z)

In [ ]:
rint = (np.bincount(Z).argmax())
rint

In [ ]:
np.where(Z == rint)[0]

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。

In [ ]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))

In [ ]:
## 進階版

def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))